# Generated by Django 5.2.12 on 2026-10-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_project_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("prototype", "Prototype"),
                    ("beta", "Beta"),
                    ("stable", "Stable"),
                ],
                default="prototype",
                max_length=20,
            ),
        ),
    ]
